### ISSUE TITLE
ImageEditor is broken with resizable modals enabled

### ISSUE THREAD

**Issue by bnf** [qbus-agentur/typo3-resizable-modals#2]
No interaction possible.

Error in console:
```
ImageManipulation.js?bust=1637312986:formatted:185 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'options')
    at ImageManipulation.js?bust=1637312986:formatted:185
```

**Comment by plojewski** [comment]
@bnf I have exactly the same error. Was it possible to somehow eliminate it?

**Comment by plojewski** [comment]
Oh, I see the fix in 1.0.1. When will this version be in the repository and composer?

**Comment by bnf** [comment]
I forgot to upload to TER, done now: https://extensions.typo3.org/extension/resizable_modals

The tag for Compoer/Packagist was already available:
https://packagist.org/packages/qbus/typo3-resizable-modals#1.0.1

**Comment by plojewski** [comment]
Thank you :)
